apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "food-classifier"
  annotations:
    serving.kserve.io/enable-metric-aggregation: "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
    autoscaling.knative.dev/target: "1"
spec:
  predictor:
    minReplicas: 2
    maxReplicas: 2
    containerConcurrency: 2
    canaryTrafficPercent: 100
    serviceAccountName: s3-read-only
    pytorch:
      protocolVersion: v1
      storageUri: s3://mybucket-emlo-mumbai/kserve-ig/cat-classifier/
      # storageUri: s3://tsai-emlo/kserve-ig/fakeimagenet-vit/
      image: pytorch/torchserve-kfs:0.12.0
      resources:
        limits:
          cpu: 2600m
          memory: 4Gi
      env:
        - name: TS_DISABLE_TOKEN_AUTHORIZATION
          value: "true" 
